export const experiences = [
  {
    id: 0,
    img: "https://th.bing.com/th/id/OIP.KI7CPS6rEnf72k5xjyZabAHaHa?rs=1&pid=ImgDetMain",
    role: "Full Stack Developer",
    company: "InfoTech Edge",
    date: "Dec 2024 - Present",
    desc: "At InfoTech Edge, I am leading the development of scalable web applications, including a Job Portal and a Content Management System. I Leveraged RTK Query and GraphQL with Apollo Client in the Job Portal web app to optimize data fetching and state management, reducing API latency and boosting client-server efficiency by 35%. Integrated an advanced rich text editor into the Learning Management System, while implementing SEO optimization and server-side rendering using Next.js and TypeScript, resulting in a 20% increase in organic traffic. Designed and optimized custom microservices with Node.js and Express, integrated JWT for secure user authentication, and implemented rate limiting and API throttling, which enhanced system stability and boosted user satisfaction, ultimately leading to a 40% revenue growth.",
    skills: [
      "Next",
      "Tailwind CSS",
      "TypeScript",
      "Express",
      "MongoDb",
      "Node",
      "GitHub",
    ],
    // doc: "https://drive.google.com/file/d/1MsWUfiUB3ZojpQY3GH_tspdnTsE0ENCg/view",
    // cert: "https://cdn.create.vista.com/downloads/37a1c116-6794-4ba6-91f0-1405596e8d69_360.jpeg",
  },
  {
    id: 0,
    img: "https://th.bing.com/th/id/OIP.qR0KDokgaurg027argTSLQAAAA?rs=1&pid=ImgDetMain",
    role: "Full Stack Web Developer",
    company: "One XL Universe",
    date: "Jun 2024 - Dec 2024",
    desc: "During my tenure at One XL Universe, I played a pivotal role in designing and developing a Social Media Management System and an Ad Management System. As a full-stack developer, I engineered both the front-end and back-end, utilizing React.js, Redux, MongoDB, and Node.js. I optimized application performance, improved scalability, and enhanced user interactions through Tailwind CSS. My work on ensuring data consistency and implementing real-time functionality contributed significantly to system stability and usability.",
    skills: [
      "React",
      "Redux",
      "Tailwind CSS",
      "Express",
      "MongoDb",
      "Node",
      "BitBucket",
    ],
    // doc: "https://drive.google.com/file/d/1MsWUfiUB3ZojpQY3GH_tspdnTsE0ENCg/view",
    // cert: "https://cdn.create.vista.com/downloads/37a1c116-6794-4ba6-91f0-1405596e8d69_360.jpeg",
  },
  {
    id: 0,
    img: "https://media.licdn.com/dms/image/D4D0BAQG-GHUu-09EjA/company-logo_200_200/0/1691427837439/focus_realm_logo?e=2147483647&v=beta&t=Lb5TzpayZrWtu0GordOUlHGtKtzoyS1y8SOoiX1eJXo",
    role: "Full Stack Developer Intern",
    company: "Focus Realm",
    date: "Jan 2024 - Mar 2024",
    desc: "As a Junior Full Stack Developer at Focus Realm, I contributed to the development of the Productivity & Wellness Management platform. I worked with React.js and Next.js to build responsive UIs while leveraging Express.js and MongoDB to create a scalable backend. I collaborated closely with design and product teams to ensure a seamless user experience and delivered features that supported the overall functionality of the platform, enhancing user engagement and application efficiency.",
    skills: [
      "React",
      "Next",
      "Tailwind CSS",
      "TypeScript",
      "Express",
      "MongoDb",
      "Node",
    ],
    // doc: "https://drive.google.com/file/d/1MsWUfiUB3ZojpQY3GH_tspdnTsE0ENCg/view",
    // cert: "https://cdn.create.vista.com/downloads/37a1c116-6794-4ba6-91f0-1405596e8d69_360.jpeg",
  },
  {
    id: 3,
    img: "https://techcult.com/wp-content/uploads/2022/11/best-freelancing-websites-for-beginners.png",
    role: "Freelance Developer & Designer",
    company: "Freelance",
    date: "Sep 2023 - Dec 2023",
    desc: "As a Freelance Developer & Designer, I delivered custom web solutions to clients, focusing on both MERN stack and WordPress platforms. I created dynamic, responsive websites, implementing backend services using Node.js and MongoDB, and designed intuitive front-end interfaces with React.js and Tailwind CSS. By tailoring each project to client specifications, I delivered fully customized, high-performance applications with a focus on user experience and functionality, ensuring seamless deployments and long-term maintainability.",
    skills: [
      "MERN Stack",
      "React",
      "WordPress",
      "Blogger",
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  // {
  //   id: 2,
  //   img: "https://firebasestorage.googleapis.com/v0/b/flexi-coding.appspot.com/o/girlScript.jpeg?alt=media&token=e656a621-cf3c-4230-bf0f-e74b4cec6035",
  //   role: "Open Source Contributor ",
  //   company: "GirlScript Summer of Code",
  //   date: "Jun 2023 - Present",
  //   desc: "Contributing to different open-source projects and learn from industry experts",
  //   // doc: "https://media.licdn.com/dms/image/D4D22AQGzSpgFaR4hsQ/feedshare-shrink_800/0/1684079632872?e=1687996800&v=beta&t=i0xWn_k32Oj9SxKfc6rARSbOghXD9Ge6WyEb2p2vvrc",
  // },
];
