export const experiences = [
  {
    id: 0,
    img: "https://media.licdn.com/dms/image/D4D0BAQG-GHUu-09EjA/company-logo_200_200/0/1691427837439/focus_realm_logo?e=2147483647&v=beta&t=Lb5TzpayZrWtu0GordOUlHGtKtzoyS1y8SOoiX1eJXo",
    role: "Junior Full Stack Developer",
    company: "Focus Realm",
    date: "Jan 2024 - Mar 2024",
    desc: "Led the development of a fully functional website using the MERN stack, bringing Figma designs to life with React for the frontend and integrating MongoDB, Express, and Node.js for a robust backend. Demonstrated expertise in end-to-end web development, ensuring a seamless user experience. Pioneered the entire development process, bringing the envisioned design to life and showcasing the project on GitHub for collaborative engagement.",
    skills: [
      "React",
      "Next",
      "Tailwind CSS",
      "TypeScript",
      "Express",
      "MongoDb",
      "Node",
      "Netlify",
      "GitHub",
      "Material UI",
      "Figma",
      "Vercel",
    ],
    doc: "https://drive.google.com/file/d/1MsWUfiUB3ZojpQY3GH_tspdnTsE0ENCg/view",
    cert: "https://cdn.create.vista.com/downloads/37a1c116-6794-4ba6-91f0-1405596e8d69_360.jpeg",
  },
  {
    id: 1,
    img: "https://media.licdn.com/dms/image/D560BAQEZKRKOWBcJ_A/company-logo_200_200/0/1706735138636/octanetsolutions_logo?e=2147483647&v=beta&t=x4pBgtyLAr0gBAUCImcbOCCmhOTWB8B8dkXMSA5lde0",
    role: "Web Development Intern",
    company: "Octanet Services",
    date: "Feb 2024 - Mar 2024",
    desc: "Worked as a Web Development Intern at Octanet Services. Spearheaded end-to-end development using React.js, HTML, CSS, JavaScript, Node.js, MongoDB.",
    skills: ["HTML", "CSS", "JavaScript", "MongoDB"],
    doc: "https://certificate.givemycertificate.com/c/18b64a26-088b-4b9e-88af-d6a154e4b438",

    cert: "https://cdn.create.vista.com/downloads/37a1c116-6794-4ba6-91f0-1405596e8d69_360.jpeg",
  },
  {
    id: 2,
    img: "https://media.licdn.com/dms/image/C5622AQH7vzV5aFxnAQ/feedshare-shrink_800/0/1677698736997?e=2147483647&v=beta&t=eikRaemWKRWC3Q4B06TIZYNqmZ3_FykTwfm8zJer6Wc",
    role: "Full Stack Web Developer Intern",
    company: "Bharat Intern",
    date: "Jan 2024 - Jan 2024",
    desc: "Engineered a money tracker for efficient financial transaction logging. Developed dynamic content management systems for easy blog post.",
    skills: [
      "React.js",
      "HTML5",
      "CSS",
      "JavsScript",
      "Express JS",
      "Mongo DB",
    ],
    doc: "https://drive.google.com/file/d/1D5P6t5pFOMxBKJVuXRN5go-uFc9Pn7Nu/view",
    cert: "https://cdn.create.vista.com/downloads/37a1c116-6794-4ba6-91f0-1405596e8d69_360.jpeg",
  },
  {
    id: 3,
    img: "https://techcult.com/wp-content/uploads/2022/11/best-freelancing-websites-for-beginners.png",
    role: "Freelance Developer & Designer",
    company: "Freelance",
    date: "Jul 2023 - Dec 2023",
    desc: "Freelanced as a full stack web developer, designed and developed websites using MERN Stack & WordPress to create dynamic and engaging online experiences. Demonstrated versatility in adapting to different platforms, showcasing a commitment to delivering customized solutions for clients.",
    skills: [
      "MERN Stack",
      "React",
      "WordPress",
      "Blogger",
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  {
    id: 2,
    img: "https://firebasestorage.googleapis.com/v0/b/flexi-coding.appspot.com/o/girlScript.jpeg?alt=media&token=e656a621-cf3c-4230-bf0f-e74b4cec6035",
    role: "Open Source Contributor ",
    company: "GirlScript Summer of Code",
    date: "Jun 2023 - Present",
    desc: "Contributing to different open-source projects and learn from industry experts",
    // doc: "https://media.licdn.com/dms/image/D4D22AQGzSpgFaR4hsQ/feedshare-shrink_800/0/1684079632872?e=1687996800&v=beta&t=i0xWn_k32Oj9SxKfc6rARSbOghXD9Ge6WyEb2p2vvrc",
  },
];
